PrimitiveDataTypeDemo2 d2 = new PrimitiveDataTypeDemo2();

d2.printNewDate();
d2.printNewTime();
d2.printNewDateTime();









//Nasıl kendi zamanımı alırım. 
// TimeZone tz = UserInfo.getTimeZone();
// DateTime dt = Datetime.now();

// system.debug('Actual Time as String ' + dt.format());
// system.debug('Offset ' + tz.getOffset(dt)/1000);
// system.debug('Formatted Time ' + dt.addSeconds((tz.getOffset(dt)/1000)));